-- This file is generated by scripts/generate-schema-sql.mjs.
-- Edit files under src/db/schema-parts/ instead.
-- 出来事種別マスタ: events.event_type が参照する種別一覧
CREATE TABLE `event_types` (
  `code` text PRIMARY KEY NOT NULL, -- 種別コード: general / war / rebellion / civil_war
  `label` text NOT NULL, -- 表示名
  `description` text -- 種別の説明
);

-- 出来事: 歴史上の事件・出来事の基本情報
CREATE TABLE `events` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 出来事ID
  `title` text NOT NULL, -- 出来事名
  `event_type` text NOT NULL REFERENCES `event_types`(`code`), -- 出来事種別コード
  `description` text, -- 出来事の説明
  `note` text, -- 編集メモ・注釈
  `from_calendar_era` text, -- 開始年の紀元区分: BCE / CE
  `from_year` integer, -- 開始年
  `from_is_approximate` integer DEFAULT false, -- 開始年がおおよそか
  `to_calendar_era` text, -- 終了年の紀元区分: BCE / CE
  `to_year` integer, -- 終了年
  `to_is_approximate` integer DEFAULT false, -- 終了年がおおよそか
  `created_at` integer NOT NULL, -- 作成日時のUnixタイムスタンプ
  `updated_at` integer NOT NULL -- 更新日時のUnixタイムスタンプ
);

-- 出来事間の関連: 出来事どうしの因果・前後関係
CREATE TABLE `event_relations` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 関連ID
  `from_event_id` integer NOT NULL, -- 起点となる出来事ID
  `to_event_id` integer NOT NULL, -- 終点となる出来事ID
  `relation_type` text NOT NULL -- 関連種別: before / after / cause / related
);

-- 戦争や反乱の参加主体: 紛争イベントに参加した主体
CREATE TABLE `event_conflict_participants` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 参加記録ID
  `event_id` integer NOT NULL, -- 対象イベントID
  `participant_type` text NOT NULL, -- 参加主体の種別: person / polity / religion / sect
  `participant_id` integer NOT NULL, -- 参加主体のID
  `role` text NOT NULL, -- 参加時の役割: attacker / defender / leader / ally / other
  `description` text, -- 参加内容の説明
  `note` text -- 編集メモ・注釈
);

-- 戦争や反乱の結果要約: 紛争イベントの勝敗と帰結の要約
CREATE TABLE `event_conflict_outcomes` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 結果要約ID
  `event_id` integer NOT NULL, -- 対象イベントID
  `resolution_summary` text, -- 全体としてどう終わったか
  `winner_summary` text, -- 勝者側が何を得たか
  `loser_summary` text -- 敗者側が何を失ったか
);

-- 戦争や反乱の勝者側・敗者側の参加主体: 結果における陣営別参加主体
CREATE TABLE `event_conflict_outcome_participants` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 結果参加主体ID
  `event_id` integer NOT NULL, -- 対象イベントID
  `side` text NOT NULL, -- 陣営: winner / loser
  `participant_type` text NOT NULL, -- 参加主体の種別: person / polity / religion / sect
  `participant_id` integer NOT NULL -- 参加主体のID
);

-- 時代区分カテゴリ: 時代区分の分類軸
CREATE TABLE `period_categories` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- カテゴリID
  `name` text NOT NULL, -- カテゴリ名
  `reading` text, -- 読み方
  `description` text -- カテゴリの説明
);

-- 時代区分: 歴史時代・期間の記録
CREATE TABLE `historical_periods` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 時代区分ID
  `name` text NOT NULL, -- 時代区分名
  `reading` text, -- 読み方
  `region_label` text, -- 表示用の地域ラベル
  `aliases` text, -- 別名のカンマ区切り文字列
  `description` text, -- 時代区分の説明
  `note` text, -- 編集メモ・注釈
  `from_calendar_era` text, -- 開始年の紀元区分: BCE / CE
  `from_year` integer, -- 開始年
  `from_is_approximate` integer DEFAULT false, -- 開始年がおおよそか
  `to_calendar_era` text, -- 終了年の紀元区分: BCE / CE
  `to_year` integer, -- 終了年
  `to_is_approximate` integer DEFAULT false -- 終了年がおおよそか
);

-- 時代区分間関係: 時代区分どうしの関係
CREATE TABLE `historical_period_relations` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 関係ID
  `from_period_id` integer NOT NULL, -- 起点となる時代区分ID
  `to_period_id` integer NOT NULL, -- 終点となる時代区分ID
  `relation_type` text NOT NULL, -- 関係種別
  `description` text, -- 関係の説明
  `note` text -- 編集メモ・注釈
);

-- 王朝と国家の所属関係
CREATE TABLE `dynasty_polity_links` (
  `dynasty_id` integer NOT NULL, -- 王朝ID
  `polity_id` integer NOT NULL -- 国家ID
);

-- 役職と人物の関連
CREATE TABLE `role_assignment_person_links` (
  `role_assignment_id` integer NOT NULL, -- 役職記録ID
  `person_id` integer NOT NULL -- 人物ID
);

-- 役職と国家の関連
CREATE TABLE `role_assignment_polity_links` (
  `role_assignment_id` integer NOT NULL, -- 役職記録ID
  `polity_id` integer NOT NULL -- 国家ID
);

-- 役職と王朝の関連
CREATE TABLE `role_assignment_dynasty_links` (
  `role_assignment_id` integer NOT NULL, -- 役職記録ID
  `dynasty_id` integer NOT NULL -- 王朝ID
);

-- 時代区分とカテゴリの関連
CREATE TABLE `historical_period_category_links` (
  `period_id` integer NOT NULL, -- 時代区分ID
  `category_id` integer NOT NULL -- カテゴリID
);

-- 時代区分と国家の関連
CREATE TABLE `historical_period_polity_links` (
  `period_id` integer NOT NULL, -- 時代区分ID
  `polity_id` integer NOT NULL -- 国家ID
);

-- 宗派と宗教の所属関係
CREATE TABLE `sect_religion_links` (
  `sect_id` integer NOT NULL, -- 宗派ID
  `religion_id` integer NOT NULL -- 宗教ID
);

-- 宗派の親子関係
CREATE TABLE `sect_parent_links` (
  `sect_id` integer NOT NULL, -- 子宗派ID
  `parent_sect_id` integer NOT NULL -- 親宗派ID
);

-- 出来事と国家の関連
CREATE TABLE `event_polity_links` (
  `event_id` integer NOT NULL, -- 出来事ID
  `polity_id` integer NOT NULL -- 国家ID
);

-- 出来事と王朝の関連
CREATE TABLE `event_dynasty_links` (
  `event_id` integer NOT NULL, -- 出来事ID
  `dynasty_id` integer NOT NULL -- 王朝ID
);

-- 出来事と時代区分の関連
CREATE TABLE `event_period_links` (
  `event_id` integer NOT NULL, -- 出来事ID
  `period_id` integer NOT NULL -- 時代区分ID
);

-- 出来事と宗教の関連
CREATE TABLE `event_religion_links` (
  `event_id` integer NOT NULL, -- 出来事ID
  `religion_id` integer NOT NULL -- 宗教ID
);

-- 出来事と宗派の関連
CREATE TABLE `event_sect_links` (
  `event_id` integer NOT NULL, -- 出来事ID
  `sect_id` integer NOT NULL -- 宗派ID
);

-- 出来事と地域の関連
CREATE TABLE `event_region_links` (
  `event_id` integer NOT NULL, -- 出来事ID
  `region_id` integer NOT NULL -- 地域ID
);

-- 出来事とタグの関連
CREATE TABLE `event_tag_links` (
  `event_id` integer NOT NULL, -- 出来事ID
  `tag_id` integer NOT NULL -- タグID
);

-- 国家と地域の関連
CREATE TABLE `polity_region_links` (
  `polity_id` integer NOT NULL, -- 国家ID
  `region_id` integer NOT NULL -- 地域ID
);

-- 王朝と地域の関連
CREATE TABLE `dynasty_region_links` (
  `dynasty_id` integer NOT NULL, -- 王朝ID
  `region_id` integer NOT NULL -- 地域ID
);

-- 時代区分と地域の関連
CREATE TABLE `period_region_links` (
  `period_id` integer NOT NULL, -- 時代区分ID
  `region_id` integer NOT NULL -- 地域ID
);

-- 宗教と地域の関連
CREATE TABLE `religion_region_links` (
  `religion_id` integer NOT NULL, -- 宗教ID
  `region_id` integer NOT NULL -- 地域ID
);

-- 宗派と地域の関連
CREATE TABLE `sect_region_links` (
  `sect_id` integer NOT NULL, -- 宗派ID
  `region_id` integer NOT NULL -- 地域ID
);

-- 宗教と開祖人物の関連
CREATE TABLE `religion_founder_links` (
  `religion_id` integer NOT NULL, -- 宗教ID
  `person_id` integer NOT NULL -- 開祖人物ID
);

-- 宗派と開祖人物の関連
CREATE TABLE `sect_founder_links` (
  `sect_id` integer NOT NULL, -- 宗派ID
  `person_id` integer NOT NULL -- 開祖人物ID
);
