-- This file is generated by scripts/generate-schema-sql.mjs.
-- Edit files under src/db/schema-parts/ instead.
-- 出来事種別マスタ: events.event_type が参照する種別一覧
CREATE TABLE `event_types` (
  `code` text PRIMARY KEY NOT NULL, -- 種別コード
  `label` text NOT NULL, -- 表示名
  `description` text -- 種別の説明
);

-- 紀元マスタ: from_calendar_era / to_calendar_era が参照する紀元区分
CREATE TABLE `era` (
  `code` text PRIMARY KEY NOT NULL, -- 紀元コード: BCE / CE
  `label` text NOT NULL, -- 表示名
  `description` text -- 紀元区分の説明
);

-- 出来事関連種別マスタ: event_relations.relation_type が参照する関連種別
CREATE TABLE `event_relation_types` (
  `code` text PRIMARY KEY NOT NULL, -- 関連種別コード: before / after / cause / related
  `label` text NOT NULL, -- 表示名
  `description` text -- 関連種別の説明
);

-- 紛争参加主体種別マスタ: participant_type が参照する主体種別
CREATE TABLE `event_conflict_participant_types` (
  `code` text PRIMARY KEY NOT NULL, -- 参加主体種別コード: person / polity / religion / sect
  `label` text NOT NULL, -- 表示名
  `description` text -- 参加主体種別の説明
);

-- 紛争参加役割マスタ: event_conflict_participants.role が参照する役割
CREATE TABLE `event_conflict_participant_roles` (
  `code` text PRIMARY KEY NOT NULL, -- 役割コード: attacker / defender / leader / ally / other
  `label` text NOT NULL, -- 表示名
  `description` text -- 役割の説明
);

-- 紛争結果陣営マスタ: event_conflict_outcome_participants.side が参照する陣営
CREATE TABLE `event_conflict_sides` (
  `code` text PRIMARY KEY NOT NULL, -- 陣営コード: winner / loser
  `label` text NOT NULL, -- 表示名
  `description` text -- 陣営の説明
);

-- 時代区分関係種別マスタ: historical_period_relations.relation_type が参照する関係種別
CREATE TABLE `historical_period_relation_types` (
  `code` text PRIMARY KEY NOT NULL, -- 関係種別コード: precedes / succeeds / overlaps / includes / included_in
  `label` text NOT NULL, -- 表示名
  `description` text -- 関係種別の説明
);

-- 国家変遷種別マスタ: polity_transitions.transition_type が参照する変遷種別
CREATE TABLE `polity_transition_types` (
  `code` text PRIMARY KEY NOT NULL, -- 変遷種別コード: renamed / succeeded / merged / split / annexed / absorbed / restored / reorganized / other
  `label` text NOT NULL, -- 表示名
  `description` text -- 変遷種別の説明
);

-- 変更履歴操作種別マスタ: change_histories.action が参照する操作種別
CREATE TABLE `change_history_actions` (
  `code` text PRIMARY KEY NOT NULL, -- 操作種別コード: create / update / delete / import
  `label` text NOT NULL, -- 表示名
  `description` text -- 操作種別の説明
);

-- 出来事: 歴史上の事件・出来事の基本情報
CREATE TABLE `events` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 出来事ID
  `title` text NOT NULL, -- 出来事名
  `event_type` text NOT NULL REFERENCES `event_types`(`code`), -- 出来事種別コード
  `description` text, -- 出来事の説明
  `note` text, -- 編集メモ・注釈
  `from_calendar_era` text REFERENCES `era`(`code`), -- 開始年の紀元区分コード
  `from_year` integer, -- 開始年
  `from_is_approximate` integer DEFAULT false, -- 開始年がおおよそか
  `to_calendar_era` text REFERENCES `era`(`code`), -- 終了年の紀元区分コード
  `to_year` integer, -- 終了年
  `to_is_approximate` integer DEFAULT false -- 終了年がおおよそか
);

-- 出来事間の関連: 出来事どうしの因果・前後関係
CREATE TABLE `event_relations` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 関連ID
  `from_event_id` integer NOT NULL REFERENCES `events`(`id`), -- 起点となる出来事ID
  `to_event_id` integer NOT NULL REFERENCES `events`(`id`), -- 終点となる出来事ID
  `relation_type` text NOT NULL REFERENCES `event_relation_types`(`code`) -- 関連種別コード
);
CREATE INDEX `idx_event_relations_from_event_id` ON `event_relations` (`from_event_id`);
CREATE INDEX `idx_event_relations_to_event_id` ON `event_relations` (`to_event_id`);

-- 戦争や反乱の参加主体: 紛争イベントに参加した主体
CREATE TABLE `event_conflict_participants` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 参加記録ID
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 対象イベントID
  `participant_type` text NOT NULL REFERENCES `event_conflict_participant_types`(`code`), -- 参加主体種別コード
  `participant_id` integer NOT NULL, -- 参加主体のID
  `role` text NOT NULL REFERENCES `event_conflict_participant_roles`(`code`), -- 参加時の役割コード
  `description` text, -- 参加内容の説明
  `note` text -- 編集メモ・注釈
);
CREATE INDEX `idx_event_conflict_participants_event_id` ON `event_conflict_participants` (`event_id`);

-- 戦争や反乱の結果要約: 紛争イベントの勝敗と帰結の要約
CREATE TABLE `event_conflict_outcomes` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 結果要約ID
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 対象イベントID
  `resolution_summary` text, -- 全体としてどう終わったか
  `winner_summary` text, -- 勝者側が何を得たか
  `loser_summary` text -- 敗者側が何を失ったか
);
CREATE INDEX `idx_event_conflict_outcomes_event_id` ON `event_conflict_outcomes` (`event_id`);

-- 戦争や反乱の勝者側・敗者側の参加主体: 結果における陣営別参加主体
CREATE TABLE `event_conflict_outcome_participants` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 結果参加主体ID
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 対象イベントID
  `side` text NOT NULL REFERENCES `event_conflict_sides`(`code`), -- 陣営コード
  `participant_type` text NOT NULL REFERENCES `event_conflict_participant_types`(`code`), -- 参加主体種別コード
  `participant_id` integer NOT NULL -- 参加主体のID
);
CREATE INDEX `idx_event_conflict_outcome_participants_event_id` ON `event_conflict_outcome_participants` (`event_id`);

-- 人物: 人物の基本情報
CREATE TABLE `persons` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 人物ID
  `name` text NOT NULL, -- 人物名
  `reading` text, -- 読み方
  `aliases` text, -- 別名のカンマ区切り文字列
  `description` text, -- 人物の説明
  `note` text, -- 編集メモ・注釈
  `from_calendar_era` text REFERENCES `era`(`code`), -- 生年の紀元区分コード
  `from_year` integer, -- 生年
  `from_is_approximate` integer DEFAULT false, -- 生年がおおよそか
  `to_calendar_era` text REFERENCES `era`(`code`), -- 没年の紀元区分コード
  `to_year` integer, -- 没年
  `to_is_approximate` integer DEFAULT false -- 没年がおおよそか
);

-- 役職: 人物が持った役職・地位の記録
CREATE TABLE `roles` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 役職記録ID
  `title` text NOT NULL, -- 役職名
  `reading` text, -- 読み方
  `description` text, -- 役職記録の説明
  `note` text -- 編集メモ・注釈
);

-- 人物と地域の関連
CREATE TABLE `person_region_links` (
  `person_id` integer NOT NULL REFERENCES `persons`(`id`), -- 人物ID
  `region_id` integer NOT NULL REFERENCES `regions`(`id`) -- 地域ID
);
CREATE INDEX `idx_person_region_links_person_id` ON `person_region_links` (`person_id`);
CREATE INDEX `idx_person_region_links_region_id` ON `person_region_links` (`region_id`);

-- 人物と宗教の関連
CREATE TABLE `person_religion_links` (
  `person_id` integer NOT NULL REFERENCES `persons`(`id`), -- 人物ID
  `religion_id` integer NOT NULL REFERENCES `religions`(`id`) -- 宗教ID
);
CREATE INDEX `idx_person_religion_links_person_id` ON `person_religion_links` (`person_id`);
CREATE INDEX `idx_person_religion_links_religion_id` ON `person_religion_links` (`religion_id`);

-- 人物と宗派の関連
CREATE TABLE `person_sect_links` (
  `person_id` integer NOT NULL REFERENCES `persons`(`id`), -- 人物ID
  `sect_id` integer NOT NULL REFERENCES `sects`(`id`) -- 宗派ID
);
CREATE INDEX `idx_person_sect_links_person_id` ON `person_sect_links` (`person_id`);
CREATE INDEX `idx_person_sect_links_sect_id` ON `person_sect_links` (`sect_id`);

-- 人物と役職の関連
CREATE TABLE `role_polity_links` (
  `role_id` integer NOT NULL REFERENCES `roles`(`id`) ON DELETE CASCADE, -- 役職記録ID
  `polity_id` integer NOT NULL REFERENCES `polities`(`id`) ON DELETE CASCADE -- 国家ID
);
CREATE INDEX `idx_role_polity_links_role_id` ON `role_polity_links` (`role_id`);
CREATE INDEX `idx_role_polity_links_polity_id` ON `role_polity_links` (`polity_id`);

-- 役職とタグの関連
CREATE TABLE `role_tag_links` (
  `role_id` integer NOT NULL REFERENCES `roles`(`id`) ON DELETE CASCADE, -- 役職記録ID
  `tag_id` integer NOT NULL REFERENCES `tags`(`id`) ON DELETE CASCADE -- タグID
);
CREATE INDEX `idx_role_tag_links_role_id` ON `role_tag_links` (`role_id`);
CREATE INDEX `idx_role_tag_links_tag_id` ON `role_tag_links` (`tag_id`);

-- 人物と役職の関連
CREATE TABLE `person_role_links` (
  `person_id` integer NOT NULL REFERENCES `persons`(`id`) ON DELETE CASCADE, -- 人物ID
  `role_id` integer NOT NULL REFERENCES `roles`(`id`), -- 役職記録ID
  `description` text, -- 人物ごとの役職説明
  `note` text, -- 人物ごとの役職メモ
  `from_calendar_era` text REFERENCES `era`(`code`), -- 開始年の紀元区分コード
  `from_year` integer, -- 開始年
  `from_is_approximate` integer DEFAULT false, -- 開始年がおおよそか
  `to_calendar_era` text REFERENCES `era`(`code`), -- 終了年の紀元区分コード
  `to_year` integer, -- 終了年
  `to_is_approximate` integer DEFAULT false -- 終了年がおおよそか
);
CREATE INDEX `idx_person_role_links_person_id` ON `person_role_links` (`person_id`);
CREATE INDEX `idx_person_role_links_role_id` ON `person_role_links` (`role_id`);

-- 時代区分カテゴリ: 時代区分の分類軸
CREATE TABLE `period_categories` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- カテゴリID
  `name` text NOT NULL, -- カテゴリ名
  `reading` text, -- 読み方
  `description` text -- カテゴリの説明
);

-- 時代区分: 歴史時代・期間の記録
CREATE TABLE `historical_periods` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 時代区分ID
  `name` text NOT NULL, -- 時代区分名
  `reading` text, -- 読み方
  `description` text, -- 時代区分の説明
  `note` text, -- 編集メモ・注釈
  `from_calendar_era` text REFERENCES `era`(`code`), -- 開始年の紀元区分コード
  `from_year` integer, -- 開始年
  `from_is_approximate` integer DEFAULT false, -- 開始年がおおよそか
  `to_calendar_era` text REFERENCES `era`(`code`), -- 終了年の紀元区分コード
  `to_year` integer, -- 終了年
  `to_is_approximate` integer DEFAULT false -- 終了年がおおよそか
);

-- 時代区分間関係: 時代区分どうしの関係
CREATE TABLE `historical_period_relations` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 関係ID
  `from_period_id` integer NOT NULL REFERENCES `historical_periods`(`id`), -- 起点となる時代区分ID
  `to_period_id` integer NOT NULL REFERENCES `historical_periods`(`id`), -- 終点となる時代区分ID
  `relation_type` text NOT NULL REFERENCES `historical_period_relation_types`(`code`), -- 関係種別コード
  `description` text, -- 関係の説明
  `note` text -- 編集メモ・注釈
);
CREATE INDEX `idx_historical_period_relations_from_period_id` ON `historical_period_relations` (`from_period_id`);
CREATE INDEX `idx_historical_period_relations_to_period_id` ON `historical_period_relations` (`to_period_id`);

-- 時代区分と地域の関連
CREATE TABLE `historical_period_region_links` (
  `period_id` integer NOT NULL REFERENCES `historical_periods`(`id`), -- 時代区分ID
  `region_id` integer NOT NULL REFERENCES `regions`(`id`) -- 地域ID
);
CREATE INDEX `idx_historical_period_region_links_period_id` ON `historical_period_region_links` (`period_id`);
CREATE INDEX `idx_historical_period_region_links_region_id` ON `historical_period_region_links` (`region_id`);

-- 時代区分とカテゴリの関連
CREATE TABLE `historical_period_category_links` (
  `period_id` integer NOT NULL REFERENCES `historical_periods`(`id`), -- 時代区分ID
  `category_id` integer NOT NULL REFERENCES `period_categories`(`id`) -- カテゴリID
);
CREATE INDEX `idx_historical_period_category_links_period_id` ON `historical_period_category_links` (`period_id`);
CREATE INDEX `idx_historical_period_category_links_category_id` ON `historical_period_category_links` (`category_id`);

-- 時代区分と国家の関連
CREATE TABLE `historical_period_polity_links` (
  `period_id` integer NOT NULL REFERENCES `historical_periods`(`id`), -- 時代区分ID
  `polity_id` integer NOT NULL REFERENCES `polities`(`id`) -- 国家ID
);
CREATE INDEX `idx_historical_period_polity_links_period_id` ON `historical_period_polity_links` (`period_id`);
CREATE INDEX `idx_historical_period_polity_links_polity_id` ON `historical_period_polity_links` (`polity_id`);

-- 地域: 地理的な分類単位
CREATE TABLE `regions` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 地域ID
  `name` text NOT NULL, -- 地域名
  `parent_region_id` integer REFERENCES `regions`(`id`), -- 親地域ID
  `reading` text, -- 読み方
  `description` text, -- 地域の説明
  `note` text -- 編集メモ・注釈
);

-- 国家: 国家・政体の基本情報
CREATE TABLE `polities` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 国家ID
  `name` text NOT NULL, -- 国家名
  `reading` text, -- 読み方
  `description` text, -- 国家の説明
  `note` text, -- 編集メモ・注釈
  `from_calendar_era` text REFERENCES `era`(`code`), -- 成立年の紀元区分コード
  `from_year` integer, -- 成立年
  `from_is_approximate` integer DEFAULT false, -- 成立年がおおよそか
  `to_calendar_era` text REFERENCES `era`(`code`), -- 終了年の紀元区分コード
  `to_year` integer, -- 終了年
  `to_is_approximate` integer DEFAULT false -- 終了年がおおよそか
);

-- 国家変遷: 前身国家と後継国家の関係
CREATE TABLE `polity_transitions` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 国家変遷ID
  `predecessor_polity_id` integer NOT NULL REFERENCES `polities`(`id`), -- 前身国家ID
  `successor_polity_id` integer NOT NULL REFERENCES `polities`(`id`), -- 後継国家ID
  `transition_type` text NOT NULL REFERENCES `polity_transition_types`(`code`) -- 変遷種別コード
);
CREATE INDEX `idx_polity_transitions_predecessor_polity_id` ON `polity_transitions` (`predecessor_polity_id`);
CREATE INDEX `idx_polity_transitions_successor_polity_id` ON `polity_transitions` (`successor_polity_id`);

-- 王朝: 王朝・王家・支配家門の基本情報
CREATE TABLE `dynasties` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 王朝ID
  `name` text NOT NULL, -- 王朝名
  `reading` text, -- 読み方
  `description` text, -- 王朝の説明
  `note` text, -- 編集メモ・注釈
  `from_calendar_era` text REFERENCES `era`(`code`), -- 開始年の紀元区分コード
  `from_year` integer, -- 開始年
  `from_is_approximate` integer DEFAULT false, -- 開始年がおおよそか
  `to_calendar_era` text REFERENCES `era`(`code`), -- 終了年の紀元区分コード
  `to_year` integer, -- 終了年
  `to_is_approximate` integer DEFAULT false -- 終了年がおおよそか
);

-- 王朝継承: 同一国家内での王朝交代
CREATE TABLE `dynasty_successions` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 王朝継承ID
  `polity_id` integer NOT NULL REFERENCES `polities`(`id`), -- 対象国家ID
  `predecessor_dynasty_id` integer NOT NULL REFERENCES `dynasties`(`id`), -- 先行王朝ID
  `successor_dynasty_id` integer NOT NULL REFERENCES `dynasties`(`id`) -- 後継王朝ID
);
CREATE INDEX `idx_dynasty_successions_polity_id` ON `dynasty_successions` (`polity_id`);
CREATE INDEX `idx_dynasty_successions_predecessor_dynasty_id` ON `dynasty_successions` (`predecessor_dynasty_id`);
CREATE INDEX `idx_dynasty_successions_successor_dynasty_id` ON `dynasty_successions` (`successor_dynasty_id`);

-- 国家と地域の関連
CREATE TABLE `polity_region_links` (
  `polity_id` integer NOT NULL REFERENCES `polities`(`id`), -- 国家ID
  `region_id` integer NOT NULL REFERENCES `regions`(`id`) -- 地域ID
);
CREATE INDEX `idx_polity_region_links_polity_id` ON `polity_region_links` (`polity_id`);
CREATE INDEX `idx_polity_region_links_region_id` ON `polity_region_links` (`region_id`);

-- 国家とタグの関連
CREATE TABLE `polity_tag_links` (
  `polity_id` integer NOT NULL REFERENCES `polities`(`id`) ON DELETE CASCADE, -- 国家ID
  `tag_id` integer NOT NULL REFERENCES `tags`(`id`) ON DELETE CASCADE -- タグID
);
CREATE INDEX `idx_polity_tag_links_polity_id` ON `polity_tag_links` (`polity_id`);
CREATE INDEX `idx_polity_tag_links_tag_id` ON `polity_tag_links` (`tag_id`);

-- 王朝と国家の関係
CREATE TABLE `dynasty_polity_links` (
  `dynasty_id` integer NOT NULL REFERENCES `dynasties`(`id`), -- 王朝ID
  `polity_id` integer NOT NULL REFERENCES `polities`(`id`) -- 国家ID
);
CREATE INDEX `idx_dynasty_polity_links_dynasty_id` ON `dynasty_polity_links` (`dynasty_id`);
CREATE INDEX `idx_dynasty_polity_links_polity_id` ON `dynasty_polity_links` (`polity_id`);

-- 王朝と地域の関連
CREATE TABLE `dynasty_region_links` (
  `dynasty_id` integer NOT NULL REFERENCES `dynasties`(`id`), -- 王朝ID
  `region_id` integer NOT NULL REFERENCES `regions`(`id`) -- 地域ID
);
CREATE INDEX `idx_dynasty_region_links_dynasty_id` ON `dynasty_region_links` (`dynasty_id`);
CREATE INDEX `idx_dynasty_region_links_region_id` ON `dynasty_region_links` (`region_id`);

-- 王朝とタグの関連
CREATE TABLE `dynasty_tag_links` (
  `dynasty_id` integer NOT NULL REFERENCES `dynasties`(`id`) ON DELETE CASCADE, -- 王朝ID
  `tag_id` integer NOT NULL REFERENCES `tags`(`id`) ON DELETE CASCADE -- タグID
);
CREATE INDEX `idx_dynasty_tag_links_dynasty_id` ON `dynasty_tag_links` (`dynasty_id`);
CREATE INDEX `idx_dynasty_tag_links_tag_id` ON `dynasty_tag_links` (`tag_id`);

-- 宗教: 宗教本体の基本情報
CREATE TABLE `religions` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 宗教ID
  `name` text NOT NULL, -- 宗教名
  `reading` text, -- 読み方
  `description` text, -- 宗教の説明
  `note` text, -- 編集メモ・注釈
  `from_calendar_era` text REFERENCES `era`(`code`), -- 成立年の紀元区分コード
  `from_year` integer, -- 成立年
  `from_is_approximate` integer DEFAULT false, -- 成立年がおおよそか
  `to_calendar_era` text REFERENCES `era`(`code`), -- 終了年の紀元区分コード
  `to_year` integer, -- 終了年
  `to_is_approximate` integer DEFAULT false -- 終了年がおおよそか
);

-- 宗派: 宗教に属する宗派・分派の基本情報
CREATE TABLE `sects` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 宗派ID
  `name` text NOT NULL, -- 宗派名
  `religion_id` integer REFERENCES `religions`(`id`), -- 所属宗教ID
  `reading` text, -- 読み方
  `description` text, -- 宗派の説明
  `note` text, -- 編集メモ・注釈
  `from_calendar_era` text REFERENCES `era`(`code`), -- 成立年の紀元区分コード
  `from_year` integer, -- 成立年
  `from_is_approximate` integer DEFAULT false, -- 成立年がおおよそか
  `to_calendar_era` text REFERENCES `era`(`code`), -- 終了年の紀元区分コード
  `to_year` integer, -- 終了年
  `to_is_approximate` integer DEFAULT false -- 終了年がおおよそか
);

-- 宗教と開祖人物の関連
CREATE TABLE `religion_founder_links` (
  `religion_id` integer NOT NULL REFERENCES `religions`(`id`), -- 宗教ID
  `person_id` integer NOT NULL REFERENCES `persons`(`id`) -- 開祖人物ID
);
CREATE INDEX `idx_religion_founder_links_religion_id` ON `religion_founder_links` (`religion_id`);
CREATE INDEX `idx_religion_founder_links_person_id` ON `religion_founder_links` (`person_id`);

-- 宗派と開祖人物の関連
CREATE TABLE `sect_founder_links` (
  `sect_id` integer NOT NULL REFERENCES `sects`(`id`), -- 宗派ID
  `person_id` integer NOT NULL REFERENCES `persons`(`id`) -- 開祖人物ID
);
CREATE INDEX `idx_sect_founder_links_sect_id` ON `sect_founder_links` (`sect_id`);
CREATE INDEX `idx_sect_founder_links_person_id` ON `sect_founder_links` (`person_id`);

-- 出典: 書誌情報のマスタ
CREATE TABLE `sources` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 出典ID
  `title` text NOT NULL, -- 出典タイトル
  `author` text, -- 著者・編者
  `publisher` text, -- 出版者・発行主体
  `published_at_label` text, -- 出典の刊行日（表示用文字列）
  `url` text, -- 参照URL
  `description` text, -- 出典の説明
  `note` text -- 編集メモ・注釈
);

-- 引用: 出典を各エンティティへ紐づける参照記録
CREATE TABLE `citations` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 引用ID
  `source_id` integer NOT NULL, -- 出典ID
  `target_type` text NOT NULL, -- 参照先のエンティティ種別
  `target_id` integer NOT NULL, -- 参照先のエンティティID
  `locator` text, -- ページ・巻・章などの参照位置
  `quote` text, -- 引用文
  `description` text, -- 引用の説明
  `note` text -- 編集メモ・注釈
);

-- タグ: 出来事などへ付与する分類タグ
CREATE TABLE `tags` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- タグID
  `name` text NOT NULL, -- タグ名
  `reading` text -- 読み方
);

-- 変更履歴: 各エンティティの変更前スナップショット
CREATE TABLE `change_histories` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- 変更履歴ID
  `target_type` text NOT NULL, -- 対象エンティティ種別
  `target_id` integer NOT NULL, -- 対象エンティティID
  `action` text NOT NULL REFERENCES `change_history_actions`(`code`), -- 操作種別コード
  `snapshot_json` text NOT NULL, -- 変更前後比較用のJSONスナップショット
  `changed_at` integer NOT NULL -- 変更日時のUnixタイムスタンプ
);

-- インポート実行履歴: CSVなどの取り込み実行記録
CREATE TABLE `import_runs` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- インポート実行ID
  `source_format` text NOT NULL, -- 入力形式: csv など
  `target_type` text NOT NULL, -- 取り込み対象の種別
  `action` text NOT NULL, -- 実行種別: preview / apply など
  `file_name` text, -- 入力ファイル名
  `status` text NOT NULL, -- 実行結果ステータス
  `summary_json` text NOT NULL -- 実行結果サマリのJSON
);

-- 出来事と人物の関連
CREATE TABLE `event_person_links` (
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 出来事ID
  `person_id` integer NOT NULL REFERENCES `persons`(`id`) -- 人物ID
);
CREATE INDEX `idx_event_person_links_event_id` ON `event_person_links` (`event_id`);
CREATE INDEX `idx_event_person_links_person_id` ON `event_person_links` (`person_id`);

-- 出来事と国家の関連
CREATE TABLE `event_polity_links` (
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 出来事ID
  `polity_id` integer NOT NULL REFERENCES `polities`(`id`) -- 国家ID
);
CREATE INDEX `idx_event_polity_links_event_id` ON `event_polity_links` (`event_id`);
CREATE INDEX `idx_event_polity_links_polity_id` ON `event_polity_links` (`polity_id`);

-- 出来事と王朝の関連
CREATE TABLE `event_dynasty_links` (
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 出来事ID
  `dynasty_id` integer NOT NULL REFERENCES `dynasties`(`id`) -- 王朝ID
);
CREATE INDEX `idx_event_dynasty_links_event_id` ON `event_dynasty_links` (`event_id`);
CREATE INDEX `idx_event_dynasty_links_dynasty_id` ON `event_dynasty_links` (`dynasty_id`);

-- 出来事と宗教の関連
CREATE TABLE `event_religion_links` (
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 出来事ID
  `religion_id` integer NOT NULL REFERENCES `religions`(`id`) -- 宗教ID
);
CREATE INDEX `idx_event_religion_links_event_id` ON `event_religion_links` (`event_id`);
CREATE INDEX `idx_event_religion_links_religion_id` ON `event_religion_links` (`religion_id`);

-- 出来事と宗派の関連
CREATE TABLE `event_sect_links` (
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 出来事ID
  `sect_id` integer NOT NULL REFERENCES `sects`(`id`) -- 宗派ID
);
CREATE INDEX `idx_event_sect_links_event_id` ON `event_sect_links` (`event_id`);
CREATE INDEX `idx_event_sect_links_sect_id` ON `event_sect_links` (`sect_id`);

-- 出来事と地域の関連
CREATE TABLE `event_region_links` (
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 出来事ID
  `region_id` integer NOT NULL REFERENCES `regions`(`id`) -- 地域ID
);
CREATE INDEX `idx_event_region_links_event_id` ON `event_region_links` (`event_id`);
CREATE INDEX `idx_event_region_links_region_id` ON `event_region_links` (`region_id`);

-- 出来事とタグの関連
CREATE TABLE `event_tag_links` (
  `event_id` integer NOT NULL REFERENCES `events`(`id`), -- 出来事ID
  `tag_id` integer NOT NULL REFERENCES `tags`(`id`) -- タグID
);
CREATE INDEX `idx_event_tag_links_event_id` ON `event_tag_links` (`event_id`);
CREATE INDEX `idx_event_tag_links_tag_id` ON `event_tag_links` (`tag_id`);
